Fixed maintainer-check rule

diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -122,5 +122,16 @@ choicetool-linker: Makefile $(srcdir)/choicetool-linker.in
 ##
 update-local: Makefile
 
-maintainer-check-local: Makefile
+maintainer-check-parameters: Makefile $(bin_SCRIPTS) $(pkgvbin_SCRIPTS)
+	for i in $(bin_SCRIPTS) $(pkgvbin_SCRIPTS) ; do \
+		echo @ECHO_N@ "Checking standard parameters for $$i... " ; \
+		if ( ./$$i -h 2>&1 > /dev/null ) ; then \
+			echo "@ECHO_T@ok" ; \
+		else \
+			echo "@ECHO_T@error" ; \
+			exit 1 ; \
+		fi ; \
+	done
+
+maintainer-check-local: Makefile maintainer-check-parameters
 	$(WHITESPACE_DETECT) $(pl_scripts_SRCS)
